title: Gökhan TAŞÇI | Sakarya Yazı İşleri Müdürü
description:  Kişisel CV
url: https://jekyll-cv.stavrospanakakis.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
